/*
 * This file is part of the PokeBoxDS project.
 * Copyright (C) 2019 Jennifer Berringer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; even with the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * This program is not in any way affiliated with Nintendo or Creatures Inc.
 * All Pokémon character names are trademarks of Nintendo and are used here
 * in accordance with the licensing information detailed at
 * <https://www.pokemon.com/us/legal/>
 */
#include "pokemon_strings.h"

#define ARRAY_LENGTH(array) (sizeof((array))/sizeof((array)[0]))

static const char *const pokemon_species[] = {
	"????????",
	"Bulbasaur",
	"Ivysaur",
	"Venusaur",
	"Charmander",
	"Charmeleon",
	"Charizard",
	"Squirtle",
	"Wartortle",
	"Blastoise",
	"Caterpie",
	"Metapod",
	"Butterfree",
	"Weedle",
	"Kakuna",
	"Beedrill",
	"Pidgey",
	"Pidgeotto",
	"Pidgeot",
	"Rattata",
	"Raticate",
	"Spearow",
	"Fearow",
	"Ekans",
	"Arbok",
	"Pikachu",
	"Raichu",
	"Sandshrew",
	"Sandslash",
	"NidoranF",
	"Nidorina",
	"Nidoqueen",
	"NidoranM",
	"Nidorino",
	"Nidoking",
	"Clefairy",
	"Clefable",
	"Vulpix",
	"Ninetales",
	"Jigglypuff",
	"Wigglytuff",
	"Zubat",
	"Golbat",
	"Oddish",
	"Gloom",
	"Vileplume",
	"Paras",
	"Parasect",
	"Venonat",
	"Venomoth",
	"Diglett",
	"Dugtrio",
	"Meowth",
	"Persian",
	"Psyduck",
	"Golduck",
	"Mankey",
	"Primeape",
	"Growlithe",
	"Arcanine",
	"Poliwag",
	"Poliwhirl",
	"Poliwrath",
	"Abra",
	"Kadabra",
	"Alakazam",
	"Machop",
	"Machoke",
	"Machamp",
	"Bellsprout",
	"Weepinbell",
	"Victreebel",
	"Tentacool",
	"Tentacruel",
	"Geodude",
	"Graveler",
	"Golem",
	"Ponyta",
	"Rapidash",
	"Slowpoke",
	"Slowbro",
	"Magnemite",
	"Magneton",
	"Farfetch'd",
	"Doduo",
	"Dodrio",
	"Seel",
	"Dewgong",
	"Grimer",
	"Muk",
	"Shellder",
	"Cloyster",
	"Gastly",
	"Haunter",
	"Gengar",
	"Onix",
	"Drowzee",
	"Hypno",
	"Krabby",
	"Kingler",
	"Voltorb",
	"Electrode",
	"Exeggcute",
	"Exeggutor",
	"Cubone",
	"Marowak",
	"Hitmonlee",
	"Hitmonchan",
	"Lickitung",
	"Koffing",
	"Weezing",
	"Rhyhorn",
	"Rhydon",
	"Chansey",
	"Tangela",
	"Kangaskhan",
	"Horsea",
	"Seadra",
	"Goldeen",
	"Seaking",
	"Staryu",
	"Starmie",
	"Mr. Mime",
	"Scyther",
	"Jynx",
	"Electabuzz",
	"Magmar",
	"Pinsir",
	"Tauros",
	"Magikarp",
	"Gyarados",
	"Lapras",
	"Ditto",
	"Eevee",
	"Vaporeon",
	"Jolteon",
	"Flareon",
	"Porygon",
	"Omanyte",
	"Omastar",
	"Kabuto",
	"Kabutops",
	"Aerodactyl",
	"Snorlax",
	"Articuno",
	"Zapdos",
	"Moltres",
	"Dratini",
	"Dragonair",
	"Dragonite",
	"Mewtwo",
	"Mew",
	"Chikorita",
	"Bayleef",
	"Meganium",
	"Cyndaquil",
	"Quilava",
	"Typhlosion",
	"Totodile",
	"Croconaw",
	"Feraligatr",
	"Sentret",
	"Furret",
	"Hoothoot",
	"Noctowl",
	"Ledyba",
	"Ledian",
	"Spinarak",
	"Ariados",
	"Crobat",
	"Chinchou",
	"Lanturn",
	"Pichu",
	"Cleffa",
	"Igglybuff",
	"Togepi",
	"Togetic",
	"Natu",
	"Xatu",
	"Mareep",
	"Flaaffy",
	"Ampharos",
	"Bellossom",
	"Marill",
	"Azumarill",
	"Sudowoodo",
	"Politoed",
	"Hoppip",
	"Skiploom",
	"Jumpluff",
	"Aipom",
	"Sunkern",
	"Sunflora",
	"Yanma",
	"Wooper",
	"Quagsire",
	"Espeon",
	"Umbreon",
	"Murkrow",
	"Slowking",
	"Misdreavus",
	"Unown-A",
	"Wobbuffet",
	"Girafarig",
	"Pineco",
	"Forretress",
	"Dunsparce",
	"Gligar",
	"Steelix",
	"Snubbull",
	"Granbull",
	"Qwilfish",
	"Scizor",
	"Shuckle",
	"Heracross",
	"Sneasel",
	"Teddiursa",
	"Ursaring",
	"Slugma",
	"Magcargo",
	"Swinub",
	"Piloswine",
	"Corsola",
	"Remoraid",
	"Octillery",
	"Delibird",
	"Mantine",
	"Skarmory",
	"Houndour",
	"Houndoom",
	"Kingdra",
	"Phanpy",
	"Donphan",
	"Porygon2",
	"Stantler",
	"Smeargle",
	"Tyrogue",
	"Hitmontop",
	"Smoochum",
	"Elekid",
	"Magby",
	"Miltank",
	"Blissey",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Pupitar",
	"Tyranitar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"?",
	"Treecko",
	"Grovyle",
	"Sceptile",
	"Torchic",
	"Combusken",
	"Blaziken",
	"Mudkip",
	"Marshtomp",
	"Swampert",
	"Poochyena",
	"Mightyena",
	"Zigzagoon",
	"Linoone",
	"Wurmple",
	"Silcoon",
	"Beautifly",
	"Cascoon",
	"Dustox",
	"Lotad",
	"Lombre",
	"Ludicolo",
	"Seedot",
	"Nuzleaf",
	"Shiftry",
	"Nincada",
	"Ninjask",
	"Shedinja",
	"Taillow",
	"Swellow",
	"Shroomish",
	"Breloom",
	"Spinda",
	"Wingull",
	"Pelipper",
	"Surskit",
	"Masquerain",
	"Wailmer",
	"Wailord",
	"Skitty",
	"Delcatty",
	"Kecleon",
	"Baltoy",
	"Claydol",
	"Nosepass",
	"Torkoal",
	"Sableye",
	"Barboach",
	"Whiscash",
	"Luvdisc",
	"Corphish",
	"Crawdaunt",
	"Feebas",
	"Milotic",
	"Carvanha",
	"Sharpedo",
	"Trapinch",
	"Vibrava",
	"Flygon",
	"Makuhita",
	"Hariyama",
	"Electrike",
	"Manectric",
	"Numel",
	"Camerupt",
	"Spheal",
	"Sealeo",
	"Walrein",
	"Cacnea",
	"Cacturne",
	"Snorunt",
	"Glalie",
	"Lunatone",
	"Solrock",
	"Azurill",
	"Spoink",
	"Grumpig",
	"Plusle",
	"Minun",
	"Mawile",
	"Meditite",
	"Medicham",
	"Swablu",
	"Altaria",
	"Wynaut",
	"Duskull",
	"Dusclops",
	"Roselia",
	"Slakoth",
	"Vigoroth",
	"Slaking",
	"Gulpin",
	"Swalot",
	"Tropius",
	"Whismur",
	"Loudred",
	"Exploud",
	"Clamperl",
	"Huntail",
	"Gorebyss",
	"Absol",
	"Shuppet",
	"Banette",
	"Seviper",
	"Zangoose",
	"Relicanth",
	"Aron",
	"Lairon",
	"Aggron",
	"Castform",
	"Volbeat",
	"Illumise",
	"Lileep",
	"Cradily",
	"Anorith",
	"Armaldo",
	"Ralts",
	"Kirlia",
	"Gardevoir",
	"Bagon",
	"Shelgon",
	"Salamence",
	"Beldum",
	"Metang",
	"Metagross",
	"Regirock",
	"Regice",
	"Registeel",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Latias",
	"Latios",
	"Jirachi",
	"Deoxys",
	"Chimecho",
	"Egg",
	"Unown-B",
	"Unown-C",
	"Unown-D",
	"Unown-E",
	"Unown-F",
	"Unown-G",
	"Unown-H",
	"Unown-I",
	"Unown-J",
	"Unown-K",
	"Unown-L",
	"Unown-M",
	"Unown-N",
	"Unown-O",
	"Unown-P",
	"Unown-Q",
	"Unown-R",
	"Unown-S",
	"Unown-T",
	"Unown-U",
	"Unown-V",
	"Unown-W",
	"Unown-X",
	"Unown-Y",
	"Unown-Z",
	"Unown-!",
	"Unown-?",
};

static const char *const move_names[] = {
	"None",
	"Pound",
	"Karate Chop",
	"Double Slap",
	"Comet Punch",
	"Mega Punch",
	"Pay Day",
	"Fire Punch",
	"Ice Punch",
	"Thunder Punch",
	"Scratch",
	"Vice Grip",
	"Guillotine",
	"Razor Wind",
	"Swords Dance",
	"Cut",
	"Gust",
	"Wing Attack",
	"Whirlwind",
	"Fly",
	"Bind",
	"Slam",
	"Vine Whip",
	"Stomp",
	"Double Kick",
	"Mega Kick",
	"Jump Kick",
	"Rolling Kick",
	"Sand Attack",
	"Headbutt",
	"Horn Attack",
	"Fury Attack",
	"Horn Drill",
	"Tackle",
	"Body Slam",
	"Wrap",
	"Take Down",
	"Thrash",
	"Double-Edge",
	"Tail Whip",
	"Poison Sting",
	"Twineedle",
	"Pin Missile",
	"Leer",
	"Bite",
	"Growl",
	"Roar",
	"Sing",
	"Supersonic",
	"Sonic Boom",
	"Disable",
	"Acid",
	"Ember",
	"Flamethrower",
	"Mist",
	"Water Gun",
	"Hydro Pump",
	"Surf",
	"Ice Beam",
	"Blizzard",
	"Psybeam",
	"Bubble Beam",
	"Aurora Beam",
	"Hyper Beam",
	"Peck",
	"Drill Peck",
	"Submission",
	"Low Kick",
	"Counter",
	"Seismic Toss",
	"Strength",
	"Absorb",
	"Mega Drain",
	"Leech Seed",
	"Growth",
	"Razor Leaf",
	"Solar Beam",
	"Poison Powder",
	"Stun Spore",
	"Sleep Powder",
	"Petal Dance",
	"String Shot",
	"Dragon Rage",
	"Fire Spin",
	"Thunder Shock",
	"Thunderbolt",
	"Thunder Wave",
	"Thunder",
	"Rock Throw",
	"Earthquake",
	"Fissure",
	"Dig",
	"Toxic",
	"Confusion",
	"Psychic",
	"Hypnosis",
	"Meditate",
	"Agility",
	"Quick Attack",
	"Rage",
	"Teleport",
	"Night Shade",
	"Mimic",
	"Screech",
	"Double Team",
	"Recover",
	"Harden",
	"Minimize",
	"Smokescreen",
	"Confuse Ray",
	"Withdraw",
	"Defense Curl",
	"Barrier",
	"Light Screen",
	"Haze",
	"Reflect",
	"Focus Energy",
	"Bide",
	"Metronome",
	"Mirror Move",
	"Self-Destruct",
	"Egg Bomb",
	"Lick",
	"Smog",
	"Sludge",
	"Bone Club",
	"Fire Blast",
	"Waterfall",
	"Clamp",
	"Swift",
	"Skull Bash",
	"Spike Cannon",
	"Constrict",
	"Amnesia",
	"Kinesis",
	"Soft-Boiled",
	"High Jump Kick",
	"Glare",
	"Dream Eater",
	"Poison Gas",
	"Barrage",
	"Leech Life",
	"Lovely Kiss",
	"Sky Attack",
	"Transform",
	"Bubble",
	"Dizzy Punch",
	"Spore",
	"Flash",
	"Psywave",
	"Splash",
	"Acid Armor",
	"Crabhammer",
	"Explosion",
	"Fury Swipes",
	"Bonemerang",
	"Rest",
	"Rock Slide",
	"Hyper Fang",
	"Sharpen",
	"Conversion",
	"Tri Attack",
	"Super Fang",
	"Slash",
	"Substitute",
	"Struggle",
	"Sketch",
	"Triple Kick",
	"Thief",
	"Spider Web",
	"Mind Reader",
	"Nightmare",
	"Flame Wheel",
	"Snore",
	"Curse",
	"Flail",
	"Conversion 2",
	"Aeroblast",
	"Cotton Spore",
	"Reversal",
	"Spite",
	"Powder Snow",
	"Protect",
	"Mach Punch",
	"Scary Face",
	"Feint Attack",
	"Sweet Kiss",
	"Belly Drum",
	"Sludge Bomb",
	"Mud-Slap",
	"Octazooka",
	"Spikes",
	"Zap Cannon",
	"Foresight",
	"Destiny Bond",
	"Perish Song",
	"Icy Wind",
	"Detect",
	"Bone Rush",
	"Lock-On",
	"Outrage",
	"Sandstorm",
	"Giga Drain",
	"Endure",
	"Charm",
	"Rollout",
	"False Swipe",
	"Swagger",
	"Milk Drink",
	"Spark",
	"Fury Cutter",
	"Steel Wing",
	"Mean Look",
	"Attract",
	"Sleep Talk",
	"Heal Bell",
	"Return",
	"Present",
	"Frustration",
	"Safeguard",
	"Pain Split",
	"Sacred Fire",
	"Magnitude",
	"Dynamic Punch",
	"Megahorn",
	"Dragon Breath",
	"Baton Pass",
	"Encore",
	"Pursuit",
	"Rapid Spin",
	"Sweet Scent",
	"Iron Tail",
	"Metal Claw",
	"Vital Throw",
	"Morning Sun",
	"Synthesis",
	"Moonlight",
	"Hidden Power",
	"Cross Chop",
	"Twister",
	"Rain Dance",
	"Sunny Day",
	"Crunch",
	"Mirror Coat",
	"Psych Up",
	"Extreme Speed",
	"Ancient Power",
	"Shadow Ball",
	"Future Sight",
	"Rock Smash",
	"Whirlpool",
	"Beat Up",
	"Fake Out",
	"Uproar",
	"Stockpile",
	"Spit Up",
	"Swallow",
	"Heat Wave",
	"Hail",
	"Torment",
	"Flatter",
	"Will-O-Wisp",
	"Memento",
	"Facade",
	"Focus Punch",
	"Smelling Salts",
	"Follow Me",
	"Nature Power",
	"Charge",
	"Taunt",
	"Helping Hand",
	"Trick",
	"Role Play",
	"Wish",
	"Assist",
	"Ingrain",
	"Superpower",
	"Magic Coat",
	"Recycle",
	"Revenge",
	"Brick Break",
	"Yawn",
	"Knock Off",
	"Endeavor",
	"Eruption",
	"Skill Swap",
	"Imprison",
	"Refresh",
	"Grudge",
	"Snatch",
	"Secret Power",
	"Dive",
	"Arm Thrust",
	"Camouflage",
	"Tail Glow",
	"Luster Purge",
	"Mist Ball",
	"Feather Dance",
	"Teeter Dance",
	"Blaze Kick",
	"Mud Sport",
	"Ice Ball",
	"Needle Arm",
	"Slack Off",
	"Hyper Voice",
	"Poison Fang",
	"Crush Claw",
	"Blast Burn",
	"Hydro Cannon",
	"Meteor Mash",
	"Astonish",
	"Weather Ball",
	"Aromatherapy",
	"Fake Tears",
	"Air Cutter",
	"Overheat",
	"Odor Sleuth",
	"Rock Tomb",
	"Silver Wind",
	"Metal Sound",
	"Grass Whistle",
	"Tickle",
	"Cosmic Power",
	"Water Spout",
	"Signal Beam",
	"Shadow Punch",
	"Extrasensory",
	"Sky Uppercut",
	"Sand Tomb",
	"Sheer Cold",
	"Muddy Water",
	"Bullet Seed",
	"Aerial Ace",
	"Icicle Spear",
	"Iron Defense",
	"Block",
	"Howl",
	"Dragon Claw",
	"Frenzy Plant",
	"Bulk Up",
	"Bounce",
	"Mud Shot",
	"Poison Tail",
	"Covet",
	"Volt Tackle",
	"Magical Leaf",
	"Water Sport",
	"Calm Mind",
	"Leaf Blade",
	"Dragon Dance",
	"Rock Blast",
	"Shock Wave",
	"Water Pulse",
	"Doom Desire",
	"Psycho Boost"
};

static const char *const item_names[] = {
	"Nothing",
	"Master Ball",
	"Ultra Ball",
	"Great Ball",
	"Poké Ball",
	"Safari Ball",
	"Net Ball",
	"Dive Ball",
	"Nest Ball",
	"Repeat Ball",
	"Timer Ball",
	"Luxury Ball",
	"Premier Ball",
	"Potion",
	"Antidote",
	"Burn Heal",
	"Ice Heal",
	"Awakening",
	"Parlyz Heal",
	"Full Restore",
	"Max Potion",
	"Hyper Potion",
	"Super Potion",
	"Full Heal",
	"Revive",
	"Max Revive",
	"Fresh Water",
	"Soda Pop",
	"Lemonade",
	"Moomoo Milk",
	"EnergyPowder",
	"Energy Root",
	"Heal Powder",
	"Revival Herb",
	"Ether",
	"Max Ether",
	"Elixir",
	"Max Elixir",
	"Lava Cookie",
	"Blue Flute",
	"Yellow Flute",
	"Red Flute",
	"Black Flute",
	"White Flute",
	"Berry Juice",
	"Sacred Ash",
	"Shoal Salt",
	"Shoal Shell",
	"Red Shard",
	"Blue Shard",
	"Yellow Shard",
	"Green Shard",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"HP Up",
	"Protein",
	"Iron",
	"Carbos",
	"Calcium",
	"Rare Candy",
	"PP Up",
	"Zinc",
	"PP Max",
	"unknown",
	"Guard Spec.",
	"Dire Hit",
	"X Attack",
	"X Defend",
	"X Speed",
	"X Accuracy",
	"X Special",
	"Poké Doll",
	"Fluffy Tail",
	"unknown",
	"Super Repel",
	"Max Repel",
	"Escape Rope",
	"Repel",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"Sun Stone",
	"Moon Stone",
	"Fire Stone",
	"Thunderstone",
	"Water Stone",
	"Leaf Stone",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"TinyMushroom",
	"Big Mushroom",
	"unknown",
	"Pearl",
	"Big Pearl",
	"Stardust",
	"Star Piece",
	"Nugget",
	"Heart Scale",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"Orange Mail",
	"Harbor Mail",
	"Glitter Mail",
	"Mech Mail",
	"Wood Mail",
	"Wave Mail",
	"Bead Mail",
	"Shadow Mail",
	"Tropic Mail",
	"Dream Mail",
	"Fab Mail",
	"Retro Mail",
	"Cheri Berry",
	"Chesto Berry",
	"Pecha Berry",
	"Rawst Berry",
	"Aspear Berry",
	"Leppa Berry",
	"Oran Berry",
	"Persim Berry",
	"Lum Berry",
	"Sitrus Berry",
	"Figy Berry",
	"Wiki Berry",
	"Mago Berry",
	"Aguav Berry",
	"Iapapa Berry",
	"Razz Berry",
	"Bluk Berry",
	"Nanab Berry",
	"Wepear Berry",
	"Pinap Berry",
	"Pomeg Berry",
	"Kelpsy Berry",
	"Qualot Berry",
	"Hondew Berry",
	"Grepa Berry",
	"Tamato Berry",
	"Cornn Berry",
	"Magost Berry",
	"Rabuta Berry",
	"Nomel Berry",
	"Spelon Berry",
	"Pamtre Berry",
	"Watmel Berry",
	"Durin Berry",
	"Belue Berry",
	"Liechi Berry",
	"Ganlon Berry",
	"Salac Berry",
	"Petaya Berry",
	"Apicot Berry",
	"Lansat Berry",
	"Starf Berry",
	"Enigma Berry",
	"unknown",
	"unknown",
	"unknown",
	"BrightPowder",
	"White Herb",
	"Macho Brace",
	"Exp. Share",
	"Quick Claw",
	"Soothe Bell",
	"Mental Herb",
	"Choice Band",
	"King's Rock",
	"SilverPowder",
	"Amulet Coin",
	"Cleanse Tag",
	"Soul Dew",
	"DeepSeaTooth",
	"DeepSeaScale",
	"Smoke Ball",
	"Everstone",
	"Focus Band",
	"Lucky Egg",
	"Scope Lens",
	"Metal Coat",
	"Leftovers",
	"Dragon Scale",
	"Light Ball",
	"Soft Sand",
	"Hard Stone",
	"Miracle Seed",
	"BlackGlasses",
	"Black Belt",
	"Magnet",
	"Mystic Water",
	"Sharp Beak",
	"Poison Barb",
	"NeverMeltIce",
	"Spell Tag",
	"TwistedSpoon",
	"Charcoal",
	"Dragon Fang",
	"Silk Scarf",
	"Up-Grade",
	"Shell Bell",
	"Sea Incense",
	"Lax Incense",
	"Lucky Punch",
	"Metal Powder",
	"Thick Club",
	"Stick",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"unknown",
	"Red Scarf",
	"Blue Scarf",
	"Pink Scarf",
	"Green Scarf",
	"Yellow Scarf",
	"Mach Bike",
	"Coin Case",
	"Itemfinder",
	"Old Rod",
	"Good Rod",
	"Super Rod",
	"S.S. Ticket",
	"Contest Pass",
	"unknown",
	"Wailmer Pail",
	"Devon Goods",
	"Soot Sack",
	"Basement Key",
	"Acro Bike",
	"Pokéblock Case",
	"Letter",
	"Eon Ticket",
	"Red Orb",
	"Blue Orb",
	"Scanner",
	"Go-Goggles",
	"Meteorite",
	"Rm. 1 Key",
	"Rm. 2 Key",
	"Rm. 4 Key",
	"Rm. 6 Key",
	"Storage Key",
	"Root Fossil",
	"Claw Fossil",
	"Devon Scope",
	"TM01",
	"TM02",
	"TM03",
	"TM04",
	"TM05",
	"TM06",
	"TM07",
	"TM08",
	"TM09",
	"TM10",
	"TM11",
	"TM12",
	"TM13",
	"TM14",
	"TM15",
	"TM16",
	"TM17",
	"TM18",
	"TM19",
	"TM20",
	"TM21",
	"TM22",
	"TM23",
	"TM24",
	"TM25",
	"TM26",
	"TM27",
	"TM28",
	"TM29",
	"TM30",
	"TM31",
	"TM32",
	"TM33",
	"TM34",
	"TM35",
	"TM36",
	"TM37",
	"TM38",
	"TM39",
	"TM40",
	"TM41",
	"TM42",
	"TM43",
	"TM44",
	"TM45",
	"TM46",
	"TM47",
	"TM48",
	"TM49",
	"TM50",
	"HM01",
	"HM02",
	"HM03",
	"HM04",
	"HM05",
	"HM06",
	"HM07",
	"HM08",
	"unknown",
	"unknown",
	"Oak's Parcel",
	"Poké Flute",
	"Secret Key",
	"Bike Voucher",
	"Gold Teeth",
	"Old Amber",
	"Card Key",
	"Lift Key",
	"Helix Fossil",
	"Dome Fossil",
	"Silph Scope",
	"Bicycle",
	"Town Map",
	"VS Seeker",
	"Fame Checker",
	"TM Case",
	"Berry Pouch",
	"Teachy TV",
	"Tri-Pass",
	"Rainbow Pass",
	"Tea",
	"MysticTicket",
	"AuroraTicket",
	"Powder Jar",
	"Ruby (item)",
	"Sapphire (item)",
	"Magma Emblem",
	"Old Sea Map"
};

static const char *const location_names[] = {
	"Littleroot Town",
	"Oldale Town",
	"Dewford Town",
	"Lavaridge Town",
	"Fallarbor Town",
	"Verdanturf Town",
	"Pacifidlog Town",
	"Petalburg City",
	"Slateport City",
	"Mauville City",
	"Rustboro City",
	"Fortree City",
	"Lilycove City",
	"Mossdeep City",
	"Sootopolis City",
	"Ever Grande City",
	"Route 101",
	"Route 102",
	"Route 103",
	"Route 104",
	"Route 105",
	"Route 106",
	"Route 107",
	"Route 108",
	"Route 109",
	"Route 110",
	"Route 111",
	"Route 112",
	"Route 113",
	"Route 114",
	"Route 115",
	"Route 116",
	"Route 117",
	"Route 118",
	"Route 119",
	"Route 120",
	"Route 121",
	"Route 122",
	"Route 123",
	"Route 124",
	"Route 125",
	"Route 126",
	"Route 127",
	"Route 128",
	"Route 129",
	"Route 130",
	"Route 131",
	"Route 132",
	"Route 133",
	"Route 134",
	"Underwater (Route 124)",
	"Underwater (Route 126)",
	"Underwater (Route 127)",
	"Underwater (Route 128)",
	"Underwater (Sootopolis City)",
	"Granite Cave",
	"Mt. Chimney",
	"Safari Zone",
	"Battle TowerRS/Battle FrontierE",
	"Petalburg Woods",
	"Rusturf Tunnel",
	"Abandoned Ship",
	"New Mauville",
	"Meteor Falls",
	"Meteor Falls (unused)",
	"Mt. Pyre",
	"Hideout (Magma HideoutR/Aqua HideoutS)",
	"Shoal Cave",
	"Seafloor Cavern",
	"Underwater (Seafloor Cavern)",
	"Victory Road",
	"Mirage Island",
	"Cave of Origin",
	"Southern Island",
	"Fiery Path",
	"Fiery Path",
	"Jagged Pass",
	"Jagged Pass",
	"Sealed Chamber",
	"Underwater (Route 134)",
	"Scorched Slab",
	"Island Cave",
	"Desert Ruins",
	"Ancient Tomb",
	"Inside of Truck",
	"Sky Pillar",
	"Secret Base",
	"Ferry",
	"Pallet Town",
	"Viridian City",
	"Pewter City",
	"Cerulean City",
	"Lavender Town",
	"Vermilion City",
	"Celadon City",
	"Fuchsia City",
	"Cinnabar Island",
	"Indigo Plateau",
	"Saffron City",
	"Route 4 (Pokémon Center)",
	"Route 10 (Pokémon Center)",
	"Route 1",
	"Route 2",
	"Route 3",
	"Route 4",
	"Route 5",
	"Route 6",
	"Route 7",
	"Route 8",
	"Route 9",
	"Route 10",
	"Route 11",
	"Route 12",
	"Route 13",
	"Route 14",
	"Route 15",
	"Route 16",
	"Route 17",
	"Route 18",
	"Route 19",
	"Route 20",
	"Route 21",
	"Route 22",
	"Route 23",
	"Route 24",
	"Route 25",
	"Viridian Forest",
	"Mt. Moon",
	"S.S. Anne",
	"Underground Path (Routes 5-6)",
	"Underground Path (Routes 7-8)",
	"Diglett's Cave",
	"Victory Road",
	"Rocket Hideout",
	"Silph Co.",
	"Pokémon Mansion",
	"Safari Zone",
	"Pokémon League",
	"Rock Tunnel",
	"Seafoam Islands",
	"Pokémon Tower",
	"Cerulean Cave",
	"Power Plant",
	"One Island",
	"Two Island",
	"Three Island",
	"Four Island",
	"Five Island",
	"Seven Island",
	"Six Island",
	"Kindle Road",
	"Treasure Beach",
	"Cape Brink",
	"Bond Bridge",
	"Three Isle Port",
	"Sevii Isle 6",
	"Sevii Isle 7",
	"Sevii Isle 8",
	"Sevii Isle 9",
	"Resort Gorgeous",
	"Water Labyrinth",
	"Five Isle Meadow",
	"Memorial Pillar",
	"Outcast Island",
	"Green Path",
	"Water Path",
	"Ruin Valley",
	"Trainer Tower (exterior)",
	"Canyon Entrance",
	"Sevault Canyon",
	"Tanoby Ruins",
	"Sevii Isle 22",
	"Sevii Isle 23",
	"Sevii Isle 24",
	"Navel Rock",
	"Mt. Ember",
	"Berry Forest",
	"Icefall Cave",
	"Rocket Warehouse",
	"Trainer Tower",
	"Dotted Hole",
	"Lost Cave",
	"Pattern Bush",
	"Altering Cave",
	"Tanoby Chambers",
	"Three Isle Path",
	"Tanoby Key",
	"Birth Island",
	"Monean Chamber",
	"Liptoo Chamber",
	"Weepth Chamber",
	"Dilford Chamber",
	"Scufib Chamber",
	"Rixy Chamber",
	"Viapois Chamber",
	"Ember Spa",
	"Celadon Dept.FRLG",
	"Aqua Hideout",
	"Magma Hideout",
	"Mirage Tower",
	"Birth Island",
	"Faraway Island",
	"Artisan Cave",
	"Marine Cave",
	"Underwater (Marine Cave)",
	"Terra Cave",
	"Underwater (Route 105)",
	"Underwater (Route 125)",
	"Underwater (Route 129)",
	"Desert Underpass",
	"Altering Cave",
	"Navel Rock",
	"Trainer Hill"
};

static const short index2dex_table_gen3[] = {
	// Treecko, Grovyle, Sceptile, Torchic, Combusken, Blaziken, Mudkip, Marshtomp
	252, 253, 254, 255, 256, 257, 258, 259,
	// Sampert, Poochyena, Mightyena, Zigzagoon, Wurmple, Silcoon, Beautifly, Cascoon
	260, 261, 262, 263, 264, 265, 266, 267,
	// Dustox, Lotad, Lombre, Ludicolo, Seedot, Nuzleaf, Shiftry
	268, 269, 270, 271, 272, 273, 274, 275,
	// Nincada, Ninjask, Shedinja, Taillow, Swellow, Shroomish, Breloom, Spinda
	290, 291, 292, 276, 277, 285, 286, 327,
	// Wingull, Pelipper, Surskit, Masquerain, Wailmer, Wailord, Skitty, Delcatty
	278, 279, 283, 284, 320, 321, 300, 301,
	// Kecleon, Baltoy, Claydol, Nosepass, Torkoal, Sableye, Barboach, Whiscash
	352, 343, 344, 299, 324, 302, 339, 340,
	// Luvdisc, Corphish, Crawdaunt, Feebas, Milotic, Carvanha, Sharpedo, Trapinch
	370, 341, 342, 349, 350, 318, 319, 328,
	// Vibrava, Flygon, Makuhita, Hariyama, Electrike, Manectric, Numel, Camerupt
	329, 330, 296, 297, 309, 310, 322, 323,
	// Spheal, Sealeo, Walrein, Cacnea, Cacturne, Snorunt, Glalie, Lunatone
	363, 364, 365, 331, 332, 361, 362, 337,
	// Solrock, Azurill, Spoink, Grumpig, Plusle, Minun, Mawile, Meditite
	338, 298, 325, 326, 311, 312, 303, 307,
	// Medicham, Swablu, Altaria, Wynaut, Duskull, Roselia, Slakoth
	308, 333, 334, 360, 355, 356, 315, 287,
	// Vigoroth, Slaking, Gulpin, Tropius, Whismur, Loudred, Exploud
	288, 289, 316, 317, 357, 293, 294, 295,
	// Clamperl, Huntail, Gorebyss, Absol, Shuppet, Banette, Seviper, Zangoose
	366, 367, 368, 359, 353, 354, 336, 335,
	// Relicanth, Aron, Lairon, Aggron, Castform, Volbeat, Illumise, Lileep
	369, 304, 305, 306, 351, 313, 314, 345,
	// Cradily, Anorith, Armaldo, Ralts, Kirlia, Gardevoir, Bagon, Shelgon
	346, 347, 348, 280, 281, 282, 371, 372,
	// Salamence, Beldum, Regirock, Regice, Registeel, Kyogre
	373, 374, 375, 376, 377, 378, 379, 382,
	// Groudon, Rayquaza, Latias, Latios, Jirachi, Deoxys, Chimecho, Egg
	383, 384, 380, 381, 385, 386, 358, 0,
};

static const short dex2index_table_gen3[] = {
	// Treecko, Grovyle, Sceptile, Torchic, Combusken, Blaziken, Mudkip, Marshtomp
	277, 278, 279, 280, 281, 282, 283, 284,
	// Sampert, Poochyena, Mightyena, Zigzagoon, Wurmple, Silcoon, Beautifly, Cascoon
	285, 286, 287, 288, 289, 290, 291, 292,
	// Dustox, Lotad, Lombre, Ludicolo, Seedot, Nuzleaf, Shiftry
	293, 294, 295, 296, 297, 298, 299, 300,
	// Taillow, Swellow, Wingull, Pelipper, Ralts, Kirlia, Gardevoir, Surskit
	304, 305, 309, 310, 392, 393, 394, 311,
	// Masquerain, Shroomish, Breloom, Slakoth, Vigorith, Slaking, Nincada, Ninjask
	312, 306, 307, 364, 365, 366, 301, 302,
	// Shedinja, Whismur, Loudred, Exploud, Makuhita, Hariyama, Azurill, Nosepass
	303, 370, 371, 372, 335, 336, 350, 320,
	// Skitty, Delcatty, Sableye, Mawile, Aron, Lairon, Aggron, Meditite
	315, 316, 322, 355, 382, 383, 384, 356,
	// Medicham, Electrike, Manectric, Plusle, Minun, Volbeat, Illumise, Roselia
	357, 337, 338, 353, 354, 386, 387, 363,
	// Gulpin, Swalot, Carvanha, Sharpedo, Wailmer, Wailord, Numel, Camerupt
	367, 368, 330, 331, 313, 314, 339, 340,
	// Torkoal, Spoink, Grumpig, Spinda, Trapinch, Vibrava, Flygon, Cacnea
	321, 351, 352, 308, 332, 333, 334, 344,
	// Cacturne, Swablu, Altaria, Zangoose, Seviper, Lunatone, Solrock, Barboach
	345, 358, 359, 380, 379, 348, 349, 323,
	// Whiscash, Corphish, Crawdaunt, Baltoy, Claydol, Lileep, Cradily, Anorith
	324, 326, 327, 318, 319, 388, 389, 390,
	// Armaldo, Feebas, Milotic, Castform, Kecleon, Shuppet, Banette, Duskull
	391, 328, 329, 385, 317, 377, 378, 361,
	// Dusclops, Tropius, Chimecho, Absol, Wynaut, Snorunt, Glalie, Spheal,
	362, 369, 411, 376, 360, 346, 347, 341,
	// Sealeo, Walrein, Clamperl, Huntail, Gorebyss, Relicanth, Luvdisc, Bagon
	342, 343, 373, 374, 375, 381, 325, 395,
	// Shelgon, Salamence, Beldum, Metang, Metagross, Regirock, Regice, Registeel
	396, 397, 398, 399, 400, 401, 402, 403,
	// Latias, Latios, Kyogre, Groudon, Rayquaza, Jirachi, Deoxys
	407, 408, 404, 405, 406, 409, 410
};

const char* get_species_name_by_index(unsigned index) {
	if (index >= ARRAY_LENGTH(pokemon_species))
		return pokemon_species[0];
	return pokemon_species[index];
}

uint16_t gen3_index_to_pokedex(unsigned index) {
	if (index <= 251) // Gen1-2
		return index;
	else if (index <= 276) // Filler "?" species
		return 0;
	else if (index <= 412) // Gen3
		return index2dex_table_gen3[index - 277];
	else if (index <= 439)
		return 201;
	else
		return 0;
}

uint16_t gen3_pokedex_to_index(unsigned species) {
	if (species <= 251) // Gen1-2
		return species;
	else if (species <= 386) // Gen3
		return dex2index_table_gen3[species - 276];
	return 0;
}

const char* get_location_name(unsigned index, unsigned origin_game) {
	if (index == 0xFE)
		return "In-Game Trade";
	if (index == 0xFF)
		return "Fateful Encounter";
	if (origin_game == 15)
		return "Orre";
	if (origin_game == 0 || origin_game > 5)
		return "Met in a trade";
	if (index >= ARRAY_LENGTH(location_names))
		return 0;
	return location_names[index];
}

const char* get_item_name(unsigned index) {
	if (index >= ARRAY_LENGTH(item_names))
		return 0;
	return item_names[index];
}

const char* get_move_name(unsigned index) {
	if (index >= ARRAY_LENGTH(move_names))
		return 0;
	return move_names[index];
}
